### ISSUE TITLE
Can not to install

### ISSUE THREAD

**Issue by kiatisak22** [tomaspavlin/clubhouse-client#2]
![image](https://user-images.githubusercontent.com/28778880/109195253-de354980-77cc-11eb-9b1b-2ed4692ada94.png)

Trace: 
  Error: https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.11.2.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (D:\work\nodejs\node_modules\yarn\lib\cli.js:141289:19)
      at Object.onceWrapper (events.js:421:28)
      at ClientRequest.emit (events.js:315:20)
      at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
      at Object.onceWrapper (events.js:421:28)
      at TLSSocket.emit (events.js:327:22)
      at TLSSocket.Socket._onTimeout (net.js:483:8)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

**Comment by tomaspavlin** [comment]
Hey, it seems that there is a problem with your internet connection. I suggest to check the network connection and try it again.

**Comment by kiatisak22** [comment]
My internet is fine The connection is normal
![image](https://user-images.githubusercontent.com/28778880/109244084-a3550500-7810-11eb-85bd-6cb5e25ce550.png)

**Comment by kiatisak22** [comment]
I was able to install it successfully using yarn install --network-timeout 1000000000. I have new problem
![image](https://user-images.githubusercontent.com/28778880/109249133-af919000-7819-11eb-9baa-6e1d92ae2781.png)

**Comment by tomaspavlin** [comment]
Please use `cd api && yarn run login` instead. I am gonna fix this in other version.

**Comment by kiatisak22** [comment]
OK. Thank.
